version: 2.1
orbs:
  ruby: circleci/ruby@2.0.1
jobs:
  build:
    machine:
      image: ubuntu-2204:2023.10.1
    steps:
      - run: sudo apt update
      - run: DEBIAN_FRONTEND=noninteractive sudo apt install rbenv
      # ruby/install - version: "3.3.0-preview2"
      - run: |
          eval "$(rbenv init -)"
      - run: rbenv install 3.3.0-preview2
      - checkout
      # ruby/install-deps
      - run: bundle install
